name: 'test'

on:
  push:

jobs:   
  test:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    needs: validate-commit-message
    if: needs.validate-commit-message.outputs.is_invalid_message == 'true'
    permissions: write-all
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: AI Code Reviewer
        uses: Shiro-nn/ai-commit-fixer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.AI_API_KEY }}
          OPENAI_API_ENDPOINT: https://integrate.api.nvidia.com/v1
          OPENAI_API_MODEL: nvidia/llama-3.3-nemotron-super-49b-v1
          OCO_PROMPT_MODULE: conventional-commit
